mybatis:
  mapper-locations: classpath:mappers/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/step?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: