# 使用多数据源无法使用默认数据标签配置, 需要解析
# 多数据源无法自动注入 mybatis mapper-locations 配置, 需要手动注入
# 多数据源配置中, 各种数据源单独占一个包, 自动注入对应的数据源, 方法中需要谨慎处理数据源交叉的情形, 需要管理事务
datasource:
  first:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test_a?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password:
  second:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test_b?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password:

# 打印执行的SQL语句, 需要指定到映射器上
logging:
  level:
    com:
      github:
        zhgxun:
          learn:
            dao:
              first:
                LaunchInfoDao: debug

# hikari 连接池配置

# mongo
spring:
  data:
    mongodb:
      uri: mongodb://test:test123@127.0.0.1/express
